{
  "Title": "Security update for python311",
  "Tracking": {
    "ID": "SUSE-SU-2024:2982-1",
    "Status": "Final",
    "Version": "1",
    "InitialReleaseDate": "2024-08-20T09:09:06Z",
    "CurrentReleaseDate": "2024-08-20T09:09:06Z",
    "RevisionHistory": [
      {
        "Number": "1",
        "Date": "2024-08-20T09:09:06Z",
        "Description": "current"
      }
    ]
  },
  "Notes": [
    {
      "Text": "Security update for python311",
      "Title": "Topic",
      "Type": "Summary"
    },
    {
      "Text": "This update for python311 fixes the following issues:\n\nSecurity issues fixed:\n\n- CVE-2024-6923: Fixed email header injection due to unquoted newlines (bsc#1228780)\n- CVE-2024-5642: Removed support for anything but OpenSSL 1.1.1 or newer (bsc#1227233)\n- CVE-2024-4032: Fixed incorrect IPv4 and IPv6 private ranges (bsc#1226448)\n\nNon-security issues fixed:\n\n- Fixed executable bits for /usr/bin/idle* (bsc#1227378).\n- Improve python reproducible builds (bsc#1227999)\n- Make pip and modern tools install directly in /usr/local when used by the user (bsc#1225660)\n- %{profileopt} variable is set according to the variable %{do_profiling} (bsc#1227999)\n",
      "Title": "Details",
      "Type": "General"
    },
    {
      "Text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "Title": "Terms of Use",
      "Type": "Legal Disclaimer"
    },
    {
      "Text": "SUSE-2024-2982,SUSE-SLE-Module-Basesystem-15-SP6-2024-2982,SUSE-SLE-Module-Python3-15-SP6-2024-2982,openSUSE-SLE-15.6-2024-2982",
      "Title": "Patchnames",
      "Type": "Details"
    }
  ],
  "ProductTree": {
    "Relationships": [
      {
        "ProductReference": "libpython3_11-1_0-3.11.9-150600.3.3.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Basesystem 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python311-base-3.11.9-150600.3.3.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Basesystem 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python311-3.11.9-150600.3.3.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Python 3 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python311-curses-3.11.9-150600.3.3.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Python 3 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python311-dbm-3.11.9-150600.3.3.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Python 3 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python311-devel-3.11.9-150600.3.3.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Python 3 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python311-idle-3.11.9-150600.3.3.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Python 3 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python311-tk-3.11.9-150600.3.3.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Python 3 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python311-tools-3.11.9-150600.3.3.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Python 3 15 SP6",
        "RelationType": "Default Component Of"
      }
    ]
  },
  "References": [
    {
      "URL": "https://www.suse.com/support/update/announcement/2024/suse-su-20242982-1/",
      "Description": "Link for SUSE-SU-2024:2982-1"
    },
    {
      "URL": "https://lists.suse.com/pipermail/sle-updates/2024-August/036645.html",
      "Description": "E-Mail link for SUSE-SU-2024:2982-1"
    },
    {
      "URL": "https://www.suse.com/support/security/rating/",
      "Description": "SUSE Security Ratings"
    },
    {
      "URL": "https://bugzilla.suse.com/1225660",
      "Description": "SUSE Bug 1225660"
    },
    {
      "URL": "https://bugzilla.suse.com/1226447",
      "Description": "SUSE Bug 1226447"
    },
    {
      "URL": "https://bugzilla.suse.com/1226448",
      "Description": "SUSE Bug 1226448"
    },
    {
      "URL": "https://bugzilla.suse.com/1227378",
      "Description": "SUSE Bug 1227378"
    },
    {
      "URL": "https://bugzilla.suse.com/1227999",
      "Description": "SUSE Bug 1227999"
    },
    {
      "URL": "https://bugzilla.suse.com/1228780",
      "Description": "SUSE Bug 1228780"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2023-27043/",
      "Description": "SUSE CVE CVE-2023-27043 page"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-0397/",
      "Description": "SUSE CVE CVE-2024-0397 page"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-4032/",
      "Description": "SUSE CVE CVE-2024-4032 page"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-6923/",
      "Description": "SUSE CVE CVE-2024-6923 page"
    }
  ],
  "Vulnerabilities": [
    {
      "CVE": "CVE-2023-27043",
      "Description": "The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2023-27043.html",
          "Description": "CVE-2023-27043"
        },
        {
          "URL": "https://bugzilla.suse.com/1210638",
          "Description": "SUSE Bug 1210638"
        },
        {
          "URL": "https://bugzilla.suse.com/1222537",
          "Description": "SUSE Bug 1222537"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Basesystem 15 SP6:libpython3_11-1_0-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Basesystem 15 SP6:python311-base-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-curses-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-dbm-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-devel-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-idle-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-tk-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-tools-3.11.9-150600.3.3.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    },
    {
      "CVE": "CVE-2024-0397",
      "Description": "A defect was discovered in the Python \"ssl\" module where there is a memory\nrace condition with the ssl.SSLContext methods \"cert_store_stats()\" and\n\"get_ca_certs()\". The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-0397.html",
          "Description": "CVE-2024-0397"
        },
        {
          "URL": "https://bugzilla.suse.com/1226447",
          "Description": "SUSE Bug 1226447"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Basesystem 15 SP6:libpython3_11-1_0-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Basesystem 15 SP6:python311-base-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-curses-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-dbm-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-devel-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-idle-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-tk-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-tools-3.11.9-150600.3.3.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    },
    {
      "CVE": "CVE-2024-4032",
      "Description": "The \"ipaddress\" module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as \"globally reachable\" or \"private\". This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn't be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-4032.html",
          "Description": "CVE-2024-4032"
        },
        {
          "URL": "https://bugzilla.suse.com/1226448",
          "Description": "SUSE Bug 1226448"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Basesystem 15 SP6:libpython3_11-1_0-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Basesystem 15 SP6:python311-base-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-curses-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-dbm-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-devel-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-idle-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-tk-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-tools-3.11.9-150600.3.3.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    },
    {
      "CVE": "CVE-2024-6923",
      "Description": "There is a MEDIUM severity vulnerability affecting CPython.\n\nThe \nemail module didn't properly quote newlines for email headers when \nserializing an email message allowing for header injection when an email\n is serialized.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-6923.html",
          "Description": "CVE-2024-6923"
        },
        {
          "URL": "https://bugzilla.suse.com/1228780",
          "Description": "SUSE Bug 1228780"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Basesystem 15 SP6:libpython3_11-1_0-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Basesystem 15 SP6:python311-base-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-curses-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-dbm-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-devel-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-idle-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-tk-3.11.9-150600.3.3.1",
            "SUSE Linux Enterprise Module for Python 3 15 SP6:python311-tools-3.11.9-150600.3.3.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    }
  ]
}