{
  "Severity": "MODERATE",
  "UpdatedAt": "2023-08-11T19:48:29Z",
  "Package": {
    "Ecosystem": "PIP",
    "Name": "GitPython"
  },
  "Advisory": {
    "DatabaseId": 218098,
    "Id": "GSA_kwCzR0hTQS1wcjc2LTVjbTUtdzljas4AA1Py",
    "GhsaId": "GHSA-pr76-5cm5-w9cj",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2023-40267"
      },
      {
        "Url": "https://github.com/gitpython-developers/GitPython/pull/1609"
      },
      {
        "Url": "https://github.com/gitpython-developers/GitPython/commit/ca965ecc81853bca7675261729143f54e5bf4cdd"
      },
      {
        "Url": "https://github.com/advisories/GHSA-pr76-5cm5-w9cj"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-pr76-5cm5-w9cj"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2023-40267"
      }
    ],
    "Description": "GitPython before 3.1.32 does not block insecure non-multi options in `clone` and `clone_from`, making it vulnerable to Remote Code Execution (RCE) due to improper user input validation, which makes it possible to inject a maliciously crafted remote URL into the clone command. Exploiting this vulnerability is possible because the library makes external calls to git without sufficient sanitization of input arguments. NOTE: this issue exists because of an incomplete fix for CVE-2022-24439.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2023-08-11T09:30:36Z",
    "Severity": "MODERATE",
    "Summary": "GitPython vulnerable to remote code execution due to insufficient sanitization of input arguments",
    "UpdatedAt": "2023-08-11T19:48:29Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 0,
      "VectorString": ""
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "3.1.32"
      },
      "VulnerableVersionRange": "\u003c 3.1.32"
    }
  ]
}