{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2023-28859",
  "PublicDate": "2023-03-26T19:15:00Z",
  "References": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28859",
    "https://github.com/redis/redis-py/pull/2641",
    "https://github.com/redis/redis-py/issues/2665"
  ],
  "Description": "redis-py before 4.4.4 and 4.5.x before 4.5.4 leaves a connection open after canceling an async Redis command at an inopportune time, and can send response data to the client of an unrelated request. (This could, for example, happen for a non-pipeline operation.) NOTE: the solutions for CVE-2023-28859 address data leakage across AsyncIO connections in general.",
  "UbuntuDescription": "",
  "Notes": null,
  "Bugs": null,
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "",
  "Patches": {
    "python-redis": {
      "bionic": {
        "Status": "needs-triage",
        "Note": ""
      },
      "devel": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-infra/xenial": {
        "Status": "needs-triage",
        "Note": ""
      },
      "focal": {
        "Status": "needs-triage",
        "Note": ""
      },
      "jammy": {
        "Status": "needs-triage",
        "Note": ""
      },
      "kinetic": {
        "Status": "needs-triage",
        "Note": ""
      },
      "lunar": {
        "Status": "needs-triage",
        "Note": ""
      },
      "trusty": {
        "Status": "ignored",
        "Note": "out of standard support"
      },
      "upstream": {
        "Status": "needs-triage",
        "Note": ""
      },
      "xenial": {
        "Status": "ignored",
        "Note": "out of standard support"
      }
    }
  },
  "UpstreamLinks": {}
}