{
  "Severity": "HIGH",
  "UpdatedAt": "2022-10-31T18:45:44Z",
  "Package": {
    "Ecosystem": "GO",
    "Name": "github.com/cloudflare/cfrpki/cmd/octorpki"
  },
  "Advisory": {
    "DatabaseId": 194969,
    "Id": "GSA_kwCzR0hTQS1wbXc5LTU2N3AtNjhwY84AAvmZ",
    "GhsaId": "GHSA-pmw9-567p-68pc",
    "References": [
      {
        "Url": "https://github.com/cloudflare/cfrpki/security/advisories/GHSA-pmw9-567p-68pc"
      },
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2022-3616"
      },
      {
        "Url": "https://github.com/cloudflare/cfrpki/commit/5f64bcd13477b29cd7ddff6fff3c65dfac3423ca"
      },
      {
        "Url": "https://github.com/advisories/GHSA-pmw9-567p-68pc"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-pmw9-567p-68pc"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2022-3616"
      }
    ],
    "Description": "### Impact\nAttackers can create long chains of CAs that would lead to OctoRPKI exceeding its max iterations parameter that would cause the program to crash and not finish the validation and thus a denial of service.\n\n### Patches\nThis issue is fixed in v1.4.4\n\n### Workarounds\nNone.\n",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2022-10-31T18:45:43Z",
    "Severity": "HIGH",
    "Summary": "OctoRPKI crashes when max iterations is reached",
    "UpdatedAt": "2023-03-29T19:13:14Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 7.5,
      "VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "1.4.4"
      },
      "VulnerableVersionRange": "\u003c= 1.4.3"
    }
  ]
}