{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2025-32414",
  "PublicDate": "2025-04-08T03:15:00Z",
  "References": [
    "https://www.cve.org/CVERecord?id=CVE-2025-32414"
  ],
  "Description": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Python API (Python bindings) because of an incorrect return value. This occurs in xmlPythonFileRead and xmlPythonFileReadRaw because of a difference between bytes and characters.",
  "UbuntuDescription": "",
  "Notes": null,
  "Bugs": [
    "https://gitlab.gnome.org/GNOME/libxml2/-/issues/889"
  ],
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "mdeslaur(main), leosilva(esm)",
  "Patches": {
    "libxml2": {
      "devel": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-infra-legacy/trusty": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-infra/bionic": {
        "Status": "needs-triage",
        "Note": ""
      },
      "esm-infra/xenial": {
        "Status": "needs-triage",
        "Note": ""
      },
      "focal": {
        "Status": "needs-triage",
        "Note": ""
      },
      "jammy": {
        "Status": "needs-triage",
        "Note": ""
      },
      "noble": {
        "Status": "needs-triage",
        "Note": ""
      },
      "oracular": {
        "Status": "needs-triage",
        "Note": ""
      },
      "plucky": {
        "Status": "needs-triage",
        "Note": ""
      },
      "upstream": {
        "Status": "needs-triage",
        "Note": ""
      }
    }
  },
  "UpstreamLinks": {
    "libxml2": [
      "https://gitlab.gnome.org/GNOME/libxml2/-/commit/8d415b8911be26b12b85497f7cc57143b5321787",
      "https://gitlab.gnome.org/GNOME/libxml2/-/commit/4d24aa22ac5811235904a02530fd8dce01c65f68 (test)"
    ]
  }
}